// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GhwfejXiMQ9WV88Ramf2JUXmnC2pVdY',
    appId: '1:375598279832:android:c4d1967613062f8b7574ed',
    messagingSenderId: '375598279832',
    projectId: 'smart-agritech-d8120',
    databaseURL: 'https://smart-agritech-d8120-default-rtdb.firebaseio.com',
    storageBucket: 'smart-agritech-d8120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_mnQj5VtK1K5nUfHN6p2ITmY1l4DHKCg',
    appId: '1:375598279832:ios:de64ac717cf82ba57574ed',
    messagingSenderId: '375598279832',
    projectId: 'smart-agritech-d8120',
    databaseURL: 'https://smart-agritech-d8120-default-rtdb.firebaseio.com',
    storageBucket: 'smart-agritech-d8120.appspot.com',
    iosBundleId: 'com.example.iotApp',
  );
}
